################################# Default configuration ###################
# provide your domain here
baseURL = "https://www.gsquash.fr"
# theme
theme = "dot"
# site title
title = "G.Squash"
# disable language
disableLanguages = []
#languageCode = "fr-fr"
defaultContentLanguage = "fr"
# google analytics
googleAnalytics = "UA-176702980-1"
# unsafe html
#[markup.goldmark.renderer]
#unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#8B0000"
body_color = "#f9f9f9"
secondary_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
#contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/groups/gsquash38/"


################################# navigation ################################
[[menu.main]]
name = "Association"
weight = 1
hasChildren = true
#
  [[menu.main]]
  parent = "Association"
  name = "Informations Association "
  url = "association/bureau"
  weight = 1

  [[menu.main]]
  parent = "Association"
  name = "Calendrier"
  url = "association/calendrier"
  weight = 2

  [[menu.main]]
  parent = "Association"
  name = "Cordage"
  url = "association/cordage"
  weight = 3

  [[menu.main]]
  parent = "Association"
  name = "Licence"
  url = "association/licence"
  weight = 4

  [[menu.main]]
  parent = "Association"
  name = "Reprise"
  url = "association/reprise"
  weight = 5

# Dropdown menu
[[menu.main]]
name = "Loisir"
weight = 2
hasChildren = true
#

  # [[menu.main]]
  # parent = "Loisir"
  # name = "Soirée squash 24/11/21"
  # url = "loisir/soiree"
  # weight = 1
  
# Dropdown menu
[[menu.main]]
weight = 3
name = "Competition"
hasChildren = true

  [[menu.main]]
  parent = "Competition"
  name = "Régionale 2 Féminine"
  url = "team/team_0"
  weight = 1

  [[menu.main]]
  parent = "Competition"
  name = "Régionale 2 Masculine"
  url = "team/team_1"
  weight = 2

  [[menu.main]]
  parent = "Competition"
  name = "Régionale 3 Masculine"
  url = "team/team_2"
  weight = 3

# Dropdown menu
[[menu.main]]
weight = 3
name = "G2S Ligue"
hasChildren = true

  [[menu.main]]
  parent = "G2S Ligue"
  name = "Réglement"
  url = "g2sligue/rules"
  weight = 1

  [[menu.main]]
  parent = "G2S Ligue"
  name = "Classement"
  url = "g2sligue/ranking"
  weight = 2

  [[menu.main]]
  parent = "G2S Ligue"
  name = "Poule"
  url = "g2sligue/poule"
  weight = 3

  [[menu.main]]
  parent = "G2S Ligue"
  name = "Inscription"
  url = "g2sligue/registration"
  weight = 4

################################### French Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
home = "Accueil"
#copyright = "Ce site est généré avec Hugo v{{ .Site.Hugo.Version }}. Avec le theme Dot."

# banner
[Languages.fr.params.banner]
title = "Bienvenue chez G.Squash"
description = "Trouvez rapidement une page"
bg_image = "images/banner.png"
placeholder = "Vous avez une question ? Il suffit de demander ici ou de saisir les termes"

# call to action
#[Languages.fr.params.cta]
#enable = true
#title = "Vous n'avez pas trouvé de réponse à votre question?"
#description = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
#[Languages.fr.params.cta.button]
#enable = true
#label = "Contactez nous"
#link = "contact"
