name: CI to build github pages
on: 
  push:
    branches: 
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout project
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: srt32/hugo-action@v0.0.3

    - name: Build
      run: hugo --minify

    - name: Deploy to GH-Pages
      uses: peaceiris/actions-gh-pages@v2
