name: CI to build github pages
on: 
  push:
    branches: 
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout project
      uses: actions/checkout@v1
#      with:
#        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
 
    - name: Build
#      run: hugo --minify
      run: hugo --theme=dot

    - name: Deploy to GH-Pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public

    - name: Create CNAME
      run: |
        echo "www2.gsquash.fr">CNAME

